# Generated by Django 3.0.3 on 2020-03-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twtposter',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='twtposter',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='twtposter',
            name='twt',
        ),
        migrations.AddField(
            model_name='twt',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twt',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twtposter',
            name='twtposter_text',
            field=models.CharField(default='emptyuser', max_length=200, verbose_name='twtposter username'),
        ),
    ]
