# Generated by Django 3.0.3 on 2020-03-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twts', '0002_auto_20200306_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='twtposter',
            name='twtposter_password',
            field=models.CharField(default='emptypassword', max_length=200, verbose_name='twtposter password'),
        ),
        migrations.AlterField(
            model_name='twtposter',
            name='twtposter_text',
            field=models.CharField(default='emptyuser', max_length=200, verbose_name='twtposter username/email'),
        ),
    ]
