# Generated by Django 3.0.3 on 2020-03-07 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twts', '0003_auto_20200306_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='twt',
            name='twtposter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='twts.TwtPoster'),
            preserve_default=False,
        ),
    ]
