# Generated by Django 3.0.3 on 2020-03-14 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twts', '0004_twt_twtposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twt',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 18, 3, 45, 332810, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.CharField(max_length=200, verbose_name='twt text')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 3, 14, 18, 3, 45, 333807, tzinfo=utc), verbose_name='date published')),
                ('reply_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twts.TwtPoster')),
                ('twt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twts.Twt')),
            ],
        ),
    ]
